#!/usr/bin/env bash
set -e

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${dir}/colorizer-lib/colorizer.sh"
source "${dir}/common"

# The correct way to call this script is inside a container built by the
# official Dockerfile at the root of the yhat/internal-scripts repo. The Dockerfile,
# and make.sh should all be from the same source code revision.

set -o pipefail

# Print a usage message and exit.
usage() {
    cat >&2 <<'EOF'

make binary-release SRC=<src>

To run, I need:
- to be in a container generated by the Dockerfile at the top of the
  yhat/hova repository;
- to be provided with the name of an S3 bucket, in environment variable
  AWS_S3_BUCKET;
- to be provided with AWS credentials for this S3 bucket, in environment
  variables AWS_ACCESS_KEY and AWS_SECRET_KEY;
- the passphrase to unlock the GPG key which will sign the deb packages
  (passed as environment variable GPG_PASSPHRASE);
- the app to be released in the first argument passed $1;
- a generous amount of good will and nice manners.
The canonical way to run me is to run the image produced by the Dockerfile: e.g.:"

make binary-release SRC=<src>

EOF
    exit 1
}

main() {
    check

    cd /
    local src=$1

    if [[ -z $src ]]; then
        usage
    fi

    set_locales
    setup_gpg

    release_binary $src

    colorize "<white>Releasing</white> <blue>${src}</blue> <white>is complete.<white>"

    exit
}

main $@
